### ISSUE TITLE
[Bug] The system navigation bar overlaps the screens content

### ISSUE THREAD

**Issue by hoangnguyen92dn** [win-than-htike/Survey#8]
When I enable the system navigation bar, the Home screen doesn’t fit the available content and overlapped by the system bar. Would it be possible to tackle this UI issue to display the content accordingly?

| With navigation bar | Without navigation bar |
|-|-|
| <img src="https://github.com/win-than-htike/Survey/assets/6950766/0735f699-2a90-44e2-b898-cb65976460ad" width=300 /> | <img src="https://github.com/win-than-htike/Survey/assets/6950766/26722d44-177d-4479-905e-9545b17eef4c" width=300 />

**Comment by win-than-htike** [comment]
I've done for this one. Please let me know if you have any comments.
