### ISSUE TITLE
[Question] Need explanation why the loading is being updated outside the Flow stream?

### ISSUE THREAD

**Issue by hoangnguyen92dn** [win-than-htike/Survey#9]
❓ From your implementation, besides onEach and catch block, can you please elaborate why the loading state is being updated outside the Flow before the UseCase is executed? Would it be feasible to handle this with `onStart` , Is there any edge-case?

https://github.com/win-than-htike/Survey/blob/70abeb2c662d3c5631bc98b92918390f975b292b/app/src/main/java/com/winthan/survey/ui/login/LoginViewModel.kt#L42-L53

https://github.com/win-than-htike/Survey/blob/70abeb2c662d3c5631bc98b92918390f975b292b/app/src/main/java/com/winthan/survey/ui/survey/SurveyDetailViewModel.kt#L41-L54

https://github.com/win-than-htike/Survey/blob/70abeb2c662d3c5631bc98b92918390f975b292b/app/src/main/java/com/winthan/survey/ui/home/HomeViewModel.kt#L50-L63

**Comment by win-than-htike** [comment]
Actually there is no edge-case for that. I will move loading block to `onStart`.

**Comment by win-than-htike** [comment]
I've done for this one. Please let me know if you have any comments.
